name: Matrix-Core Infinite Runner

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 */5 * * *'

concurrency:
  group: matrix-core-group
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish curl g++

      - name: Compile Matrix-Core
        run: |
          g++ -O3 MatriX_Core.cpp -o MatriX_Core -pthread

      - name: Execute Matrix-Core
        env:
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }}
        run: |
          chmod +x MatriX_Core
          # -E bayrağı env değişkenlerini sudo'ya taşır
          sudo -E ./MatriX_Core
